name: MKernel
version: '1.5.0'
main: net.miarma.mkernel.MKernel
api-version: '1.21'
authors: [Gallardo7761, elpapuu1333 (Contributor & tester)]
permissions:
    mkernel.command:
        description: Permite al usuario ejecutar comandos de MKernel
        default: true
    mkernel.command.reload:
        description: Permite al usuario recargar la configuración de MKernel
        default: op
    mkernel.command.config:
        description: Permite al usuario configurar los módulos de MKernel
        default: op
    mkernel.command.tpa:
        description: Permite al usuario enviar una petición de teletransporte
        default: true
    mkernel.command.tpahere:
        description: Permite al usuario enviar una petición de teletransporte a otro jugador
        default: true
    mkernel.command.tpaccept:
        description: Permite al usuario aceptar una petición de teletransporte
        default: true
    mkernel.command.tpdeny:
        description: Permite al usuario rechazar una petición de teletransporte
        default: true
    mkernel.globalchest:
        description: Permite al usuario abrir el cofre global
        default: true
    mkernel.globalchest.others:
        description: Permite al usuario abrir el cofre global de otro jugador
        default: op
    mkernel.disposal:
        description: Permite al usuario abrir el contenedor de basura
        default: true
    mkernel.disposal.others:
        description: Permite al usuario abrir el contenedor de basura de otro jugador
        default: op
    mkernel.command.sendcoords:
        description: Permite al usuario enviar sus coordenadas a otro jugador
        default: true
    mkernel.command.spawn:
        description: Permite al usuario teletransportarse al punto de spawn
        default: true
    mkernel.command.spawn.others:
        description: Permite al usuario teletransportar a otro jugador al punto de spawn
        default: op
    mkernel.command.lobby:
        description: Permite al usuario teletransportarse al lobby
        default: true
    mkernel.command.lobby.others:
        description: Permite al usuario teletransportar a otro jugador al lobby
        default: op
    mkernel.command.opme:
        description: Permite al usuario hacerse op
        default: op
    mkernel.command.deopme:
        description: Permite al usuario quitarse el op
        default: op
    mkernel.command.specialitem:
        description: Permite al usuario obtener un item especial
        default: op
    mkernel.command.blockworld:
        description: Permite al usuario bloquear un mundo
        default: op
    mkernel.command.home:
        description: Permite al usuario teletransportarse a su casa
        default: true
    mkernel.command.sethome:
        description: Permite al usuario establecer su casa
        default: true
    mkernel.command.recinv:
        description: Permite recuperar tu inventario
        default: true
    mkernel.command.gmc:
        description: Permite al usuario cambiar su modo de juego a creativo
        default: op
    mkernel.command.gms:
        description: Permite al usuario cambiar su modo de juego a supervivencia
        default: op
    mkernel.command.gma:
        description: Permite al usuario cambiar su modo de juego a aventura
        default: op
    mkernel.command.gmsp:
        description: Permite al usuario cambiar su modo de juego a espectador
        default: op
    mkernel.command.vanish:
        description: Permite al usuario volverse invisible
        default: op
    mkernel.command.warp:
        description: Permite al usuario teletransportarse a un warp
        default: true
    mkernel.command.warp.add:
        description: Permite al usuario añadir un warp
        default: true
    mkernel.command.warp.remove:
        description: Permite al usuario eliminar un warp
        default: true
    mkernel.command.spy:
        description: Permite al usuario espiar a otro jugador
        default: op
    mkernel.command.freeze:
        description: Permite al usuario congelar a otro jugador
        default: op
    mkernel.command.heal:
        description: Permite al usuario curarse
        default: true
    mkernel.command.heal.others:
        description: Permite al usuario curar a otro jugador
        default: op
    mkernel.command.launch:
        description: Permite al usuario lanzar a otro jugador
        default: op
    mkernel.command.invsee:
        description: Abre el inventario de otro jugador
        default: op

    mkernel.events.chatformat:
        description: Permite al usuario usar formatos y colores en los mensajes de chat
        default: true
    mkernel.events.adminchat:
        description: Permite al usuario usar el chat de administración
        default: op
    mkernel.events.mentions:
        description: Permite al usuario usar menciones
        default: true

    mkernel.admin:
        description: Permite al usuario ejecutar comandos de administrador
        default: op
        children:
            mkernel.command.reload: true
            mkernel.command.config: true
            mkernel.command.opme: true
            mkernel.command.deopme: true
            mkernel.command.globalchest.others: true
            mkernel.command.disposal.others: true
            mkernel.command.spawn.others: true
            mkernel.command.lobby.others: true
            mkernel.command.specialitem: true
            mkernel.command.blockworld: true
            mkernel.command.gmc: true
            mkernel.command.gms: true
            mkernel.command.gma: true
            mkernel.command.gmsp: true
            mkernel.command.vanish: true
            mkernel.command.spy: true
            mkernel.command.freeze: true
            mkernel.command.heal: true
            mkernel.command.heal.others: true
            mkernel.command.launch: true
            mkernel.command.invsee: true
            mkernel.events.adminchat: true
            mkernel.player: true

    mkernel.player:
        description: Permite al usuario ejecutar comandos de jugador
        default: true
        children:
            mkernel.command.tpa: true
            mkernel.command.tpahere: true
            mkernel.command.tpaccept: true
            mkernel.command.tpdeny: true
            mkernel.command.globalchest: true
            mkernel.command.disposal: true
            mkernel.command.sendcoords: true
            mkernel.command.spawn: true
            mkernel.command.lobby: true
            mkernel.command.home: true
            mkernel.command.sethome: true
            mkernel.events.chatformat: true
            mkernel.events.mentions: true
            mkernel.command.recinv: true
            mkernel.command.warp: true
            mkernel.command.warp.add: true
            mkernel.command.warp.remove: true
            mkernel.command.me: true
            mkernel.command.do: true
            mkernel.command.payxp: true

    mkernel.*:
        description: Permite al usuario ejecutar todos los comandos de MKernel
        default: op
        children:
            mkernel.admin: true
            mkernel.player: true